export const SET_LIST_SETTING = 'SET_LIST_SETTING';
export const RESET_LIST_SETTING = 'RESET_LIST_SETTING';
export const SELECT_PAGE = 'SELECT_PAGE';
export const SET_SIGN_IN_MODAL = 'SET_SIGN_IN_MODAL';
export const SET_SIGN_UP_MODAL = 'SET_SIGN_UP_MODAL';
export const SET_MODAL = 'SET_MODAL';
export const SET_USER_LIST_SETTING = 'SET_USER_LIST_SETTING';